### ISSUE TITLE
inputs are not loaded. stuck on loading

### ISSUE THREAD

**Issue by anergiti** [nvonkorff/TA-gmail-audit#8]
inputs are not loaded. stuck on loading...
see errors:

`05-12-2020 04:19:31.392 -0400 ERROR AdminManagerExternal - Stack trace from python handler:\nTraceback (most recent call last):\n  File "/opt/splunk/lib/python2.7/site-packages/splunk/admin.py", line 131, in init\n    hand.execute(info)\n  File "/opt/splunk/lib/python2.7/site-packages/splunk/admin.py", line 595, in execute\n    if self.requestedAction == ACTION_LIST:     self.handleList(confInfo)\n  File "/opt/splunk/etc/apps/TA-gmail-audit/bin/ta_gmail_audit/splunk_aoblib/rest_migration.py", line 38, in handleList\n    AdminExternalHandler.handleList(self, confInfo)\n  File "/opt/splunk/etc/apps/TA-gmail-audit/bin/ta_gmail_audit/splunktaucclib/rest_handler/admin_external.py", line 40, in wrapper\n    for entity in result:\n  File "/opt/splunk/etc/apps/TA-gmail-audit/bin/ta_gmail_audit/splunktaucclib/rest_handler/handler.py", line 118, in wrapper\n    raise RestError(exc.status, exc.message)\nRestError: REST Error [404]: Not Found -- HTTP 404 Not Found -- {"messages":[{"type":"ERROR","text":"Not Found"}]}\n
05-12-2020 04:19:31.437 -0400 ERROR AdminManagerExternal - Stack trace from python handler:\nTraceback (most recent call last):\n  File "/opt/splunk/lib/python2.7/site-packages/splunk/admin.py", line 131, in init\n    hand.execute(info)\n  File "/opt/splunk/lib/python2.7/site-packages/splunk/admin.py", line 595, in execute\n    if self.requestedAction == ACTION_LIST:     self.handleList(confInfo)\n  File "/opt/splunk/etc/apps/TA-gmail-audit/bin/ta_gmail_audit/splunk_aoblib/rest_migration.py", line 38, in handleList\n    AdminExternalHandler.handleList(self, confInfo)\n  File "/opt/splunk/etc/apps/TA-gmail-audit/bin/ta_gmail_audit/splunktaucclib/rest_handler/admin_external.py", line 40, in wrapper\n    for entity in result:\n  File "/opt/splunk/etc/apps/TA-gmail-audit/bin/ta_gmail_audit/splunktaucclib/rest_handler/handler.py", line 118, in wrapper\n    raise RestError(exc.status, exc.message)\nRestError: REST Error [404]: Not Found -- HTTP 404 Not Found -- {"messages":[{"type":"ERROR","text":"Not Found"}]}\n`

**Comment by nvonkorff** [comment]
Hi @anergiti 
Please try again with the latest version. These errors should now be resolved.
